import { EditorView } from "@codemirror/view";

export const readerEditorTheme = EditorView.theme({
  "&": {
    height: "100%",
    color: "var(--ink)",
    backgroundColor: "var(--paper)",
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
    fontSize: "15px",
  },
  ".cm-content": { padding: "16px 20px", caretColor: "var(--accent)" },
  '&[data-editor-profile="prose"] .cm-content, &[data-editor-profile="compact"] .cm-content': {
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
  },
  '&[data-editor-profile="code"] .cm-content': { fontFamily: "var(--mono)" },
  ".cm-line": { padding: "0", lineHeight: "1.55" },
  ".cm-cursor": { borderLeftColor: "var(--accent)" },
  ".cm-selectionBackground, &.cm-focused .cm-selectionBackground": {
    backgroundColor: "var(--selected)",
  },
  '&[data-editor-profile="prose"] .cm-gutters, &[data-editor-profile="compact"] .cm-gutters': {
    display: "none",
  },
  ".cm-gutters": {
    borderRight: "1px solid var(--line)",
    color: "var(--faint)",
    backgroundColor: "var(--canvas)",
  },
  ".cm-activeLine, .cm-activeLineGutter": {
    backgroundColor: "color-mix(in oklch, var(--accent) 5%, transparent)",
  },
  ".cm-scroller": { overflow: "auto" },
  "&.cm-focused": {
    outline: "2px solid color-mix(in oklch, var(--accent) 48%, transparent)",
    outlineOffset: "-2px",
  },
  ".cm-panels": {
    borderBottom: "1px solid var(--line-strong)",
    color: "var(--ink-soft)",
    backgroundColor: "var(--paper)",
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
    fontSize: "12px",
  },
  ".cm-search label": { color: "var(--muted)", fontSize: "11px" },
  ".cm-search input": {
    border: "1px solid var(--line-strong)",
    borderRadius: "4px",
    color: "var(--ink)",
    backgroundColor: "var(--canvas)",
  },
  ".cm-tooltip-autocomplete": {
    overflow: "hidden",
    border: "1px solid var(--line-strong)",
    borderRadius: "6px",
    backgroundColor: "var(--paper)",
    boxShadow: "0 18px 48px -24px var(--color-scrim)",
  },
  ".cm-tooltip-autocomplete > ul": {
    maxHeight: "320px",
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
  },
  ".cm-tooltip-autocomplete > ul > li": { minHeight: "48px", padding: "8px 12px" },
  ".cm-tooltip-autocomplete > ul > li[aria-selected]": {
    backgroundColor: "var(--selected)",
    color: "var(--ink)",
  },
  ".cm-completionLabel": { color: "var(--ink)", fontSize: "13px", fontWeight: "600" },
  ".cm-completionDetail": { color: "var(--muted)", fontSize: "11px", fontStyle: "normal" },
  ".cm-completionIcon": { color: "var(--accent)" },
  ".cm-wikilink.is-resolved": {
    color: "var(--accent)",
    textDecoration: "underline",
    textDecorationColor: "color-mix(in oklch, var(--accent) 35%, transparent)",
    textUnderlineOffset: "3px",
  },
  ".cm-wikilink.is-unresolved": {
    textDecoration: "underline wavy var(--danger)",
    textUnderlineOffset: "3px",
  },
  ".cm-citation-widget": {
    position: "relative",
    display: "inline-flex",
    alignItems: "baseline",
    margin: "0 2px",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
  },
  ".cm-citation-reference": {
    padding: "0 4px",
    border: "0",
    borderBottom: "1px solid color-mix(in oklch, var(--accent) 42%, transparent)",
    borderRadius: "3px",
    color: "var(--ink-soft)",
    background: "color-mix(in oklch, var(--accent) 5%, transparent)",
    font: "inherit",
    fontSize: "13px",
    lineHeight: "1.35",
    cursor: "text",
  },
  ".cm-citation-reference:hover, .cm-citation-reference:focus-visible": {
    color: "var(--ink)",
    background: "var(--selected)",
    outline: "none",
  },
  ".cm-citation-actions": {
    position: "absolute",
    top: "calc(100% + 5px)",
    left: "0",
    zIndex: "20",
    display: "flex",
    gap: "2px",
    padding: "4px",
    border: "1px solid var(--line-strong)",
    borderRadius: "5px",
    background: "var(--paper)",
    boxShadow: "0 12px 30px -18px var(--color-scrim)",
    opacity: "0",
    visibility: "hidden",
    pointerEvents: "none",
    transition: "opacity 100ms var(--ease)",
  },
  ".cm-citation-widget:hover .cm-citation-actions, .cm-citation-widget:focus-within .cm-citation-actions":
    {
      opacity: "1",
      visibility: "visible",
      pointerEvents: "auto",
    },
  ".cm-citation-actions button": {
    padding: "4px 7px",
    border: "0",
    borderRadius: "3px",
    color: "var(--ink-soft)",
    background: "transparent",
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
    fontSize: "10px",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  ".cm-citation-actions button:hover, .cm-citation-actions button:focus-visible": {
    color: "var(--ink)",
    background: "var(--hover)",
    outline: "none",
  },
  ".cm-citation-syntax.is-resolved": {
    color: "var(--accent)",
    textDecoration: "underline",
    textDecorationColor: "color-mix(in oklch, var(--accent) 30%, transparent)",
    textUnderlineOffset: "3px",
  },
  ".cm-citation-syntax.is-unresolved": {
    textDecoration: "underline wavy var(--danger)",
    textUnderlineOffset: "3px",
  },
  ".cm-diagnostic-error": { borderLeftColor: "var(--danger)" },
  ".cm-annotation-embed": {
    width: "100%",
    margin: "14px 0",
    padding: "10px 0 10px 14px",
    border: "0",
    borderLeft: "2px solid var(--accent)",
    color: "var(--ink)",
    background: "transparent",
    fontFamily: '"Atkinson Hyperlegible", "Segoe UI", sans-serif',
    whiteSpace: "normal",
  },
  ".cm-annotation-embed header, .cm-annotation-embed footer": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  ".cm-annotation-embed header span": {
    color: "var(--muted)",
    fontSize: "10px",
    fontWeight: "600",
    textTransform: "capitalize",
  },
  ".cm-annotation-embed header small": { color: "var(--muted)", fontSize: "11px" },
  ".cm-annotation-embed blockquote": {
    margin: "12px 0 8px",
    color: "var(--ink)",
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: "15px",
    lineHeight: "1.55",
  },
  ".cm-annotation-embed p": {
    margin: "8px 0",
    color: "var(--ink-soft)",
    fontSize: "13px",
    lineHeight: "1.5",
  },
  ".cm-annotation-embed footer": { marginTop: "12px" },
  ".cm-annotation-embed code": {
    overflow: "hidden",
    marginRight: "auto",
    color: "var(--faint)",
    fontFamily: "var(--mono)",
    fontSize: "9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  ".cm-annotation-embed button": {
    flex: "0 0 auto",
    padding: "5px 8px",
    borderRadius: "3px",
    color: "var(--ink-soft)",
    background: "transparent",
    fontSize: "11px",
    cursor: "pointer",
  },
  ".cm-annotation-embed button:hover": { color: "var(--ink)", background: "var(--hover)" },
  ".cm-annotation-embed button:focus-visible": {
    outline: "2px solid var(--accent)",
    outlineOffset: "2px",
  },
});
