import { useCallback, useEffect, useRef } from "react";

import type { PointerEvent as ReactPointerEvent } from "react";

const holdMs = 480;
const slopPx = 10;

export interface LongPress {
  /** Pointer handlers for one item; only touch pointers start a press. */
  readonly bind: (onLongPress: () => void) => {
    readonly onPointerDown: (event: ReactPointerEvent) => void;
    readonly onPointerMove: (event: ReactPointerEvent) => void;
    readonly onPointerUp: () => void;
    readonly onPointerCancel: () => void;
    readonly onContextMenu: (event: { preventDefault: () => void }) => void;
  };
  /** True once for the click that ends a long press, so it does not also act as a tap. */
  readonly consumeClick: () => boolean;
  /** Whether the latest press on an item was a finger's. */
  readonly touched: () => boolean;
}

/** Touch long-press: a finger held still selects, so moving it (scrolling) never does. */
export function useLongPress(): LongPress {
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const start = useRef<{ x: number; y: number } | null>(null);
  const fired = useRef(false);
  const touch = useRef(false);
  const cancel = useCallback((): void => {
    if (timer.current) {
      clearTimeout(timer.current);
    }
    timer.current = null;
    start.current = null;
  }, []);
  useEffect(() => cancel, [cancel]);
  const bind = useCallback<LongPress["bind"]>(
    (onLongPress) => ({
      onPointerDown: (event) => {
        touch.current = event.pointerType === "touch";
        if (event.pointerType !== "touch") {
          return;
        }
        cancel();
        fired.current = false;
        start.current = { x: event.clientX, y: event.clientY };
        timer.current = setTimeout(() => {
          fired.current = true;
          timer.current = null;
          // Safari has no vibration API, though the DOM types declare it.
          if ("vibrate" in globalThis.navigator) {
            globalThis.navigator.vibrate(8);
          }
          onLongPress();
        }, holdMs);
      },
      onPointerMove: (event) => {
        const origin = start.current;
        if (origin && Math.hypot(event.clientX - origin.x, event.clientY - origin.y) > slopPx) {
          cancel();
        }
      },
      onPointerUp: cancel,
      onPointerCancel: cancel,
      // Android opens a context menu on a long press; the press is ours.
      onContextMenu: (event) => {
        if (fired.current) {
          event.preventDefault();
        }
      },
    }),
    [cancel],
  );
  const consumeClick = useCallback((): boolean => {
    const was = fired.current;
    fired.current = false;
    return was;
  }, []);
  const touched = useCallback((): boolean => touch.current, []);
  return { bind, consumeClick, touched };
}

/**
 * What a click on a list item does. A mouse selects, and a double-click opens, as in a file
 * manager. A finger has no double-click, so a tap opens, unless the list is already selecting by
 * touch (after a long press), where a tap toggles. Keyboard activation and modified clicks select.
 */
export function listItemClick(input: {
  /** The click ends a long press, which has already acted. */
  readonly consumed: boolean;
  readonly touched: boolean;
  readonly touchSelecting: boolean;
  readonly modified: boolean;
  /** Generated by Enter or Space rather than a press (a click's `detail` is 0). */
  readonly keyboard: boolean;
}): "ignore" | "open" | "select" {
  if (input.consumed) {
    return "ignore";
  }
  return input.touched && !input.keyboard && !input.touchSelecting && !input.modified
    ? "open"
    : "select";
}

/** Decides a list item's click from the press that made it. */
export function itemClick(
  press: LongPress,
  event: {
    readonly detail: number;
    readonly shiftKey: boolean;
    readonly ctrlKey: boolean;
    readonly metaKey: boolean;
  },
  touchSelecting: boolean,
): "ignore" | "open" | "select" {
  return listItemClick({
    consumed: press.consumeClick(),
    touched: press.touched(),
    touchSelecting,
    modified: hasModifier(event),
    keyboard: event.detail === 0,
  });
}

/** Whether a click asks for a keyboard-modified gesture (range or toggle) rather than a tap. */
export function hasModifier(event: {
  readonly shiftKey: boolean;
  readonly ctrlKey: boolean;
  readonly metaKey: boolean;
}): boolean {
  return event.shiftKey || event.ctrlKey || event.metaKey;
}
